wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 364
hidden_dim_2:
  desc: null
  value: 339
hidden_dim_3:
  desc: null
  value: 1766
hidden_dim_4:
  desc: null
  value: 287
kern_1:
  desc: null
  value: 7
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0014080367972542055
momentum:
  desc: null
  value: 0.20565312491783028
n_epochs:
  desc: null
  value: 9
