wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 803
hidden_dim_2:
  desc: null
  value: 779
hidden_dim_3:
  desc: null
  value: 2036
hidden_dim_4:
  desc: null
  value: 99
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0020770992269504326
momentum:
  desc: null
  value: 0.8894267043649048
n_epochs:
  desc: null
  value: 2
