wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 208
hidden_dim_2:
  desc: null
  value: 838
hidden_dim_3:
  desc: null
  value: 3771
hidden_dim_4:
  desc: null
  value: 676
kern_1:
  desc: null
  value: 3
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.0004909002742508029
momentum:
  desc: null
  value: 0.6230888667883765
n_epochs:
  desc: null
  value: 6
