wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 704
hidden_dim_2:
  desc: null
  value: 999
hidden_dim_3:
  desc: null
  value: 1983
hidden_dim_4:
  desc: null
  value: 384
kern_1:
  desc: null
  value: 3
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0003171889701958689
momentum:
  desc: null
  value: 0.5825101412305889
n_epochs:
  desc: null
  value: 9
