wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 323
hidden_dim_2:
  desc: null
  value: 308
hidden_dim_3:
  desc: null
  value: 1396
hidden_dim_4:
  desc: null
  value: 117
kern_1:
  desc: null
  value: 3
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0002539472577407685
momentum:
  desc: null
  value: 0.36872652613890067
n_epochs:
  desc: null
  value: 10
