wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 660
hidden_dim_2:
  desc: null
  value: 500
hidden_dim_3:
  desc: null
  value: 2114
hidden_dim_4:
  desc: null
  value: 732
kern_1:
  desc: null
  value: 8
kern_2:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0042630150582762035
momentum:
  desc: null
  value: 0.5472699192236394
n_epochs:
  desc: null
  value: 9
