wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 483
hidden_dim_2:
  desc: null
  value: 621
hidden_dim_3:
  desc: null
  value: 3877
hidden_dim_4:
  desc: null
  value: 323
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.00037007791708530517
momentum:
  desc: null
  value: 0.10716948690227435
n_epochs:
  desc: null
  value: 6
