wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 634
hidden_dim_2:
  desc: null
  value: 833
hidden_dim_3:
  desc: null
  value: 179
hidden_dim_4:
  desc: null
  value: 565
kern_1:
  desc: null
  value: 7
kern_2:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.00037585725445298706
momentum:
  desc: null
  value: 0.3131755526738017
n_epochs:
  desc: null
  value: 6
