wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 694
hidden_dim_2:
  desc: null
  value: 816
hidden_dim_3:
  desc: null
  value: 2930
hidden_dim_4:
  desc: null
  value: 717
kern_1:
  desc: null
  value: 7
kern_2:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0006380706820910608
momentum:
  desc: null
  value: 0.4478062276157224
n_epochs:
  desc: null
  value: 7
