wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 733
hidden_dim_2:
  desc: null
  value: 128
hidden_dim_3:
  desc: null
  value: 3427
hidden_dim_4:
  desc: null
  value: 677
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0003977541648215167
momentum:
  desc: null
  value: 0.4189379362241735
n_epochs:
  desc: null
  value: 10
