wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 636
hidden_dim_2:
  desc: null
  value: 592
hidden_dim_3:
  desc: null
  value: 3638
hidden_dim_4:
  desc: null
  value: 59
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0025446356621712024
momentum:
  desc: null
  value: 0.7510848835761571
n_epochs:
  desc: null
  value: 2
