wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 626
hidden_dim_2:
  desc: null
  value: 181
hidden_dim_3:
  desc: null
  value: 1171
hidden_dim_4:
  desc: null
  value: 299
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001393555996790019
momentum:
  desc: null
  value: 0.4051200367576937
n_epochs:
  desc: null
  value: 3
