wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 72
hidden_dim_2:
  desc: null
  value: 396
hidden_dim_3:
  desc: null
  value: 620
hidden_dim_4:
  desc: null
  value: 978
kern_1:
  desc: null
  value: 2
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.00012369811663558663
momentum:
  desc: null
  value: 0.257342029157685
n_epochs:
  desc: null
  value: 9
