wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 150
hidden_dim_2:
  desc: null
  value: 522
hidden_dim_3:
  desc: null
  value: 800
hidden_dim_4:
  desc: null
  value: 438
kern_1:
  desc: null
  value: 4
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0016180388744507822
momentum:
  desc: null
  value: 0.48099518621715676
n_epochs:
  desc: null
  value: 2
