wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 627
hidden_dim_2:
  desc: null
  value: 246
hidden_dim_3:
  desc: null
  value: 974
hidden_dim_4:
  desc: null
  value: 812
kern_1:
  desc: null
  value: 2
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0015587802019940609
momentum:
  desc: null
  value: 0.8587488098559901
n_epochs:
  desc: null
  value: 6
