wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 314
hidden_dim_2:
  desc: null
  value: 577
hidden_dim_3:
  desc: null
  value: 1518
hidden_dim_4:
  desc: null
  value: 559
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0129278874684469
momentum:
  desc: null
  value: 0.4800110161396094
n_epochs:
  desc: null
  value: 10
