wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 551
hidden_dim_2:
  desc: null
  value: 981
hidden_dim_3:
  desc: null
  value: 2447
hidden_dim_4:
  desc: null
  value: 674
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 6.443209842941887e-05
momentum:
  desc: null
  value: 0.5896012280536858
n_epochs:
  desc: null
  value: 6
