wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 543
hidden_dim_2:
  desc: null
  value: 254
hidden_dim_3:
  desc: null
  value: 3385
hidden_dim_4:
  desc: null
  value: 605
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0021651970940412095
momentum:
  desc: null
  value: 0.6422617367169993
n_epochs:
  desc: null
  value: 10
