wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 810
hidden_dim_2:
  desc: null
  value: 687
hidden_dim_3:
  desc: null
  value: 3142
hidden_dim_4:
  desc: null
  value: 236
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0003212546471645856
momentum:
  desc: null
  value: 0.7584412475745451
n_epochs:
  desc: null
  value: 9
