wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 79
hidden_dim_2:
  desc: null
  value: 599
hidden_dim_3:
  desc: null
  value: 1085
hidden_dim_4:
  desc: null
  value: 291
kern_1:
  desc: null
  value: 8
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.003936900405283196
momentum:
  desc: null
  value: 0.8464490726427965
n_epochs:
  desc: null
  value: 8
