wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 283
hidden_dim_2:
  desc: null
  value: 513
hidden_dim_3:
  desc: null
  value: 509
hidden_dim_4:
  desc: null
  value: 213
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.006144393311156935
momentum:
  desc: null
  value: 0.8944400889873091
n_epochs:
  desc: null
  value: 9
