wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 543
hidden_dim_2:
  desc: null
  value: 732
hidden_dim_3:
  desc: null
  value: 1641
hidden_dim_4:
  desc: null
  value: 938
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 5.29426815685709e-05
momentum:
  desc: null
  value: 0.5343286107097444
n_epochs:
  desc: null
  value: 7
