wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 145
hidden_dim_2:
  desc: null
  value: 307
hidden_dim_3:
  desc: null
  value: 3456
hidden_dim_4:
  desc: null
  value: 460
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.04501836774390307
momentum:
  desc: null
  value: 0.28248876692157276
n_epochs:
  desc: null
  value: 7
