wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 936
hidden_dim_2:
  desc: null
  value: 757
hidden_dim_3:
  desc: null
  value: 1910
hidden_dim_4:
  desc: null
  value: 801
kern_1:
  desc: null
  value: 6
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.00047472733974120846
momentum:
  desc: null
  value: 0.29645528044555514
n_epochs:
  desc: null
  value: 6
