wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 125
hidden_dim_2:
  desc: null
  value: 202
hidden_dim_3:
  desc: null
  value: 1570
hidden_dim_4:
  desc: null
  value: 124
kern_1:
  desc: null
  value: 3
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0006256461226864061
momentum:
  desc: null
  value: 0.8148016431154382
n_epochs:
  desc: null
  value: 3
