wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 143
hidden_dim_2:
  desc: null
  value: 186
hidden_dim_3:
  desc: null
  value: 107
hidden_dim_4:
  desc: null
  value: 477
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.008167708843819725
momentum:
  desc: null
  value: 0.670392794361585
n_epochs:
  desc: null
  value: 6
