wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 78
hidden_dim_2:
  desc: null
  value: 351
hidden_dim_3:
  desc: null
  value: 56
hidden_dim_4:
  desc: null
  value: 348
kern_1:
  desc: null
  value: 8
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.009744677529554348
momentum:
  desc: null
  value: 0.4325987738787196
n_epochs:
  desc: null
  value: 4
