wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 76
hidden_dim_2:
  desc: null
  value: 579
hidden_dim_3:
  desc: null
  value: 295
hidden_dim_4:
  desc: null
  value: 614
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 8.705979271904348e-05
momentum:
  desc: null
  value: 0.11659899906014433
n_epochs:
  desc: null
  value: 10
