wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 856
hidden_dim_2:
  desc: null
  value: 65
hidden_dim_3:
  desc: null
  value: 2051
hidden_dim_4:
  desc: null
  value: 405
kern_1:
  desc: null
  value: 4
kern_2:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0005439587936402368
momentum:
  desc: null
  value: 0.6803132730095605
n_epochs:
  desc: null
  value: 7
