wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 601
hidden_dim_2:
  desc: null
  value: 708
hidden_dim_3:
  desc: null
  value: 1983
hidden_dim_4:
  desc: null
  value: 864
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0013300523923558535
momentum:
  desc: null
  value: 0.15210144437374212
n_epochs:
  desc: null
  value: 8
