wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 565
hidden_dim_2:
  desc: null
  value: 619
hidden_dim_3:
  desc: null
  value: 3926
hidden_dim_4:
  desc: null
  value: 463
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.0001071525949439294
momentum:
  desc: null
  value: 0.3201475158962671
n_epochs:
  desc: null
  value: 6
