wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 222
hidden_dim_2:
  desc: null
  value: 483
hidden_dim_3:
  desc: null
  value: 1352
hidden_dim_4:
  desc: null
  value: 571
kern_1:
  desc: null
  value: 5
kern_2:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0040051849415694485
momentum:
  desc: null
  value: 0.30528587397056334
n_epochs:
  desc: null
  value: 4
