wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 338
hidden_dim_2:
  desc: null
  value: 684
hidden_dim_3:
  desc: null
  value: 422
hidden_dim_4:
  desc: null
  value: 333
kern_1:
  desc: null
  value: 4
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.00040257491506312927
momentum:
  desc: null
  value: 0.5212059568054173
n_epochs:
  desc: null
  value: 6
