wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 951
hidden_dim_2:
  desc: null
  value: 417
hidden_dim_3:
  desc: null
  value: 3415
hidden_dim_4:
  desc: null
  value: 556
kern_1:
  desc: null
  value: 4
kern_2:
  desc: null
  value: 7
lr:
  desc: null
  value: 0.0035544752793974102
momentum:
  desc: null
  value: 0.31829316849489886
n_epochs:
  desc: null
  value: 4
