wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim_1:
  desc: null
  value: 330
hidden_dim_2:
  desc: null
  value: 366
hidden_dim_3:
  desc: null
  value: 1443
hidden_dim_4:
  desc: null
  value: 902
kern_1:
  desc: null
  value: 8
kern_2:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0014065936744489598
momentum:
  desc: null
  value: 0.7243738716925915
n_epochs:
  desc: null
  value: 10
